# Generated by Django 5.2.10 on 2026-01-12 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=100)),
                ('proveedor', models.CharField(choices=[('OPENAI', 'OpenAI (GPT)'), ('AZURE', 'Azure OpenAI'), ('OLLAMA', 'Ollama (Local)'), ('GITHUB', 'GitHub Models')], default='GITHUB', max_length=20)),
                ('api_key', models.CharField(help_text='Token de GitHub, OpenAI Key, etc.', max_length=255)),
                ('endpoint_url', models.CharField(blank=True, help_text='Solo si usa Azure u Ollama', max_length=255, null=True)),
                ('model_name', models.CharField(default='gpt-4o-mini', help_text='Ej: gpt-4o, llama-3', max_length=100)),
                ('system_prompt', models.TextField(default='Eres un asistente médico virtual de la Clínica TimeTrack. Tu objetivo es ayudar a agendar citas. Sé amable, conciso y profesional.', help_text='Instrucciones base para el comportamiento del bot.')),
                ('temperatura', models.FloatField(default=0.7, help_text='Creatividad (0.0 a 1.0)')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.BigIntegerField(db_index=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'IA'), ('system', 'Sistema')], max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
