# Generated by Django 5.2.11 on 2026-03-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='system_prompt',
            field=models.TextField(default='Eres un asistente médico virtual de la Clínica idefnova. Tu objetivo es ayudar a agendar citas. Sé amable, conciso y profesional.', help_text='Instrucciones base para el comportamiento del bot.'),
        ),
    ]
