# Generated by Django 5.2.10 on 2026-01-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disponibilidad",
            name="fecha",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
