# Generated by Django 5.2.10 on 2026-01-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0002_disponibilidad_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="disponibilidad",
            name="fecha_fin_vigencia",
            field=models.DateField(blank=True, null=True, verbose_name="Vigente hasta"),
        ),
    ]
