# Generated by Django 5.2.11 on 2026-03-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_disponibilidad_fecha_fin_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='usuario_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
