# Generated by Django 5.2.11 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0004_disponibilidad_usuario_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloqueoagenda",
            name="usuario_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="disponibilidad",
            name="fecha_inicio_vigencia",
            field=models.DateField(blank=True, null=True, verbose_name="Vigente desde"),
        ),
    ]
