# Generated by Django 4.2.27 on 2026-01-08 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="especialidad",
            options={
                "verbose_name": "Especialidad",
                "verbose_name_plural": "Especialidades",
            },
        ),
        migrations.AlterModelOptions(
            name="lugar",
            options={"verbose_name": "Lugar", "verbose_name_plural": "Lugares"},
        ),
        migrations.AlterModelOptions(
            name="profesional",
            options={
                "verbose_name": "Profesional",
                "verbose_name_plural": "Profesionales",
            },
        ),
        migrations.AlterModelOptions(
            name="servicio",
            options={"verbose_name": "Servicio", "verbose_name_plural": "Servicios"},
        ),
    ]
