# Generated by Django 5.2.10 on 2026-01-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_alter_especialidad_options_alter_lugar_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="especialidad",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
