# Generated by Django 5.2.10 on 2026-01-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_servicio_acceso_permitido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='acceso_permitido',
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipos_paciente_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
