# Generated by Django 5.2.10 on 2026-02-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_servicio_acceso_permitido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='buffer_minutos',
            field=models.IntegerField(default=0, help_text='Minutos de bloqueo automático post-cita'),
        ),
    ]
