# Generated by Django 5.2.10 on 2026-02-18 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_servicio_buffer_minutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='buffer_minutos',
        ),
    ]
