# Generated by Django 5.2.10 on 2026-02-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_remove_servicio_buffer_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='buffer_minutos',
            field=models.IntegerField(default=0, help_text='Tiempo post-cita para limpieza/notas. Bloquea agenda pero no alarga la cita.'),
        ),
    ]
