# Generated by Django 5.2.10 on 2026-01-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_desktop', models.ImageField(upload_to='banners/', verbose_name='Imagen PC (1920x1080)')),
                ('imagen_movil', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagen Móvil')),
                ('link_accion', models.URLField(blank=True, help_text='Si el banner lleva a algún lado', null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('url_externa', models.URLField(blank=True, help_text='Link de YouTube/Vimeo', null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
