# Generated by Django 5.2.12 on 2026-03-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], default='image', max_length=20)),
                ('file', models.FileField(upload_to='assets/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PortalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mi Empresa', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#2f7ecb', max_length=20)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=20)),
                ('accent_color', models.CharField(default='#34d399', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('surface_color', models.CharField(default='#efefef', max_length=20)),
                ('text_color', models.CharField(default='#0f172a', max_length=20)),
                ('border_radius', models.IntegerField(default=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('features', 'Features Strip'), ('services', 'Services'), ('how_we_work', 'How We Work'), ('values', 'Values'), ('team', 'Team'), ('testimonials', 'Testimonials'), ('videos', 'Video Gallery'), ('contact', 'Contact'), ('custom', 'Custom')], max_length=40)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
