# Generated by Django 5.2.12 on 2026-03-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_mediaasset_page_portaltheme_pagesection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagesection",
            name="type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero"),
                    ("features", "Features Strip"),
                    ("services", "Services"),
                    ("how_we_work", "How We Work"),
                    ("three_cols", "Three Columns"),
                    ("values", "Values"),
                    ("team", "Team"),
                    ("testimonials", "Testimonials"),
                    ("videos", "Video Gallery"),
                    ("contact", "Contact"),
                    ("custom", "Custom"),
                ],
                max_length=40,
            ),
        ),
    ]
