# Generated by Django 5.2.10 on 2026-01-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0003_configuracionglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nota_interna',
            field=models.TextField(blank=True, null=True, verbose_name='Nota de Recepción/Administrativa'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada'), ('NO_ASISTIO', 'No Asistió'), ('EN_SALA', 'En Sala de Espera')], db_index=True, default='PENDIENTE', max_length=20),
        ),
    ]
