# Generated by Django 5.2.10 on 2026-01-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0007_configuracionglobal_limite_inasistencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='mensaje_bloqueo_inasistencia',
            field=models.TextField(blank=True, default='Su cuenta ha sido bloqueada por inasistencias reiteradas. Contacte a la clínica.'),
        ),
    ]
