# Generated by Django 5.2.10 on 2026-02-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0008_configuracionglobal_mensaje_bloqueo_inasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada'), ('NO_ASISTIO', 'No Asistió'), ('EN_SALA', 'En Sala de Espera'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
    ]
