# Generated by Django 5.2.10 on 2026-02-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0009_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='workflow_citas',
            field=models.JSONField(default=[{'acciones': [{'label': 'Aceptar', 'requiere_motivo': False, 'target': 'ACEPTADA', 'tipo': 'success'}, {'label': 'Rechazar', 'requiere_motivo': True, 'target': 'RECHAZADA', 'tipo': 'danger'}], 'color': 'yellow', 'icon': 'FaClock', 'label': 'Por Revisar', 'slug': 'PENDIENTE'}, {'acciones': [{'label': 'Llegó a Sala', 'requiere_motivo': False, 'target': 'EN_SALA', 'tipo': 'indigo'}, {'label': 'No Asistió', 'requiere_motivo': False, 'target': 'NO_ASISTIO', 'tipo': 'gray'}, {'label': 'Cancelar', 'requiere_motivo': True, 'target': 'CANCELADA', 'tipo': 'warning'}], 'color': 'green', 'icon': 'FaCheckCircle', 'label': 'Aceptadas', 'slug': 'ACEPTADA'}, {'acciones': [{'label': 'Finalizar Atención', 'requiere_nota_medica': True, 'target': 'REALIZADA', 'tipo': 'blue'}, {'label': 'Cancelar', 'requiere_motivo': True, 'target': 'CANCELADA', 'tipo': 'warning'}], 'color': 'indigo', 'icon': 'FaHourglassHalf', 'label': 'En Sala', 'slug': 'EN_SALA'}, {'acciones': [], 'color': 'blue', 'icon': 'FaCalendarCheck', 'label': 'Realizadas', 'slug': 'REALIZADA'}, {'acciones': [], 'color': 'red', 'icon': 'FaBan', 'label': 'Canceladas', 'slug': 'CANCELADA'}, {'acciones': [], 'color': 'gray', 'icon': 'FaTimesCircle', 'label': 'Rechazadas', 'slug': 'RECHAZADA'}, {'acciones': [], 'color': 'gray', 'icon': 'FaUserClock', 'label': 'No Asistió', 'slug': 'NO_ASISTIO'}], verbose_name='Flujo de Estados Dinámico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(db_index=True, default='PENDIENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='dias_para_actualizar_datos',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='limite_inasistencias',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='max_citas_dia_paciente',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='mensaje_bloqueo_inasistencia',
            field=models.TextField(blank=True, default='Su cuenta ha sido bloqueada por inasistencias reiteradas.'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='permitir_mismo_servicio_dia',
            field=models.BooleanField(default=False),
        ),
    ]
