# Generated by Django 5.2.10 on 2026-02-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0010_configuracionglobal_workflow_citas_alter_cita_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='grupos_excepcion_antelacion',
            field=models.TextField(default='Administrador, Recepcion', help_text='Nombres de grupos que pueden saltarse la restricción de 1 hora, separados por coma.'),
        ),
    ]
