# Generated by Django 5.2.10 on 2026-02-13 21:39

import gestion_citas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0011_configuracionglobal_grupos_excepcion_antelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionglobal',
            name='workflow_citas',
            field=models.JSONField(default=gestion_citas.models.default_workflow, verbose_name='Flujo de Estados Dinámico'),
        ),
    ]
