# Generated by Django 5.2.10 on 2026-01-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditoria_crearcuenta_profesional_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crearcuenta',
            old_name='cedula',
            new_name='documento',
        ),
    ]
