# Generated by Django 5.2.10 on 2026-02-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_permisovista_nombre_vista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category_name',
            field=models.CharField(blank=True, help_text='Ej: GESTIÓN, REPORTES', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active_item',
            field=models.BooleanField(default=True),
        ),
    ]
