# Generated by Django 5.2.10 on 2026-02-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_menuitem_category_name_menuitem_is_active_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(default='TimeTrack', max_length=100)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bg_color', models.CharField(default='#0f172a', max_length=20)),
                ('accent_color', models.CharField(default='#34d399', max_length=20)),
                ('variant', models.CharField(default='floating', max_length=20)),
                ('border_radius', models.IntegerField(default=24)),
            ],
        ),
    ]
