# Generated by Django 5.2.10 on 2026-02-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sidebarbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarbranding',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
