# Generated by Django 5.2.10 on 2026-02-21 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_sidebarbranding_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearcuenta',
            name='dependientes',
            field=models.ManyToManyField(blank=True, related_name='tutores', to=settings.AUTH_USER_MODEL),
        ),
    ]
