# Generated by Django 5.2.11 on 2026-03-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_crearcuenta_dependientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarbranding',
            name='empresa_nombre',
            field=models.CharField(default='Idefnova', max_length=100),
        ),
    ]
