# Generated by Django 5.2.11 on 2026-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_sidebarbranding_empresa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(blank=True, help_text='Tipo de acción: LOGIN, UPDATE, DELETE, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Datos adicionales (antes/después, ids, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='recurso',
            field=models.CharField(blank=True, help_text='Nombre del recurso afectado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='recurso_id',
            field=models.CharField(blank=True, help_text='ID del recurso afectado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
