# Generated by Django 5.2.11 on 2026-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auditoria_accion_auditoria_ip_auditoria_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(blank=True, db_index=True, help_text='Tipo de acción: LOGIN, UPDATE, DELETE, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='modulo',
            field=models.CharField(db_index=True, default='GENERAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='recurso',
            field=models.CharField(blank=True, db_index=True, help_text='Nombre del recurso afectado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='recurso_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del recurso afectado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuario_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
