# Generated by Django 5.2.12 on 2026-03-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearcuenta',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
