# Generated by Django 5.2.12 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_crearcuenta_tenant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("role_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="tenant_memberships",
                        to="users.crearcuenta",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tenant_id", "role_name")},
            },
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(fields=["user", "tenant_id", "is_active"], name="users_tenant_user_id_4d5232_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(
                fields=["tenant_id", "role_name", "is_active"],
                name="users_tenant_tenant__97822e_idx",
            ),
        ),
    ]
