# Generated by Django 5.2.12 on 2026-03-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_tenantmembership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantmembership',
            new_name='users_tenan_user_id_e3ec75_idx',
            old_name='users_tenant_user_id_4d5232_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantmembership',
            new_name='users_tenan_tenant__7f3b17_idx',
            old_name='users_tenant_tenant__97822e_idx',
        ),
    ]
