# Generated by Django 5.2.12 on 2026-03-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0002_notification_channels_and_templates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channelproviderconfig',
            new_name='comunicacio_tenant__623b24_idx',
            old_name='chan_cfg_tenant_channel_active_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='comunicacio_tenant__d84af3_idx',
            old_name='notif_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='comunicacio_tenant__ed6553_idx',
            old_name='notif_tenant_tipo_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationtemplate',
            new_name='comunicacio_tenant__a51f0c_idx',
            old_name='notif_tpl_tenant_code_active_idx',
        ),
    ]
