# Generated by Django 5.2.12 on 2026-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0003_rename_chan_cfg_tenant_channel_active_idx_comunicacio_tenant__623b24_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelproviderconfig',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp_meta', 'WhatsApp Meta'), ('whatsapp_qr', 'WhatsApp QR'), ('sms_labsmobile', 'SMS LabsMobile'), ('sms_twilio', 'SMS Twilio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=50),
        ),
    ]
